name: odiya_bible_app
description: "Odiya Bible App - Read and meditate the WORD of GOD in Odiya"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  shared_preferences: ^2.2.3
  http: ^1.2.1
  json_annotation: ^4.9.0
  share_plus: ^9.0.0
  flutter_tts: ^4.0.2
  url_launcher: ^6.2.6
  file_picker: ^8.0.3
  xml: ^6.5.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
    - assets/JSON/
    - assets/JSON/Genesis/
    - assets/JSON/Exodus/
    - assets/JSON/Leviticus/
    - assets/JSON/Numbers/
    - assets/JSON/Deuteronomy/
    - assets/JSON/Joshua/
    - assets/JSON/Judges/
    - assets/JSON/Ruth/
    - assets/JSON/1 Samuel/
    - assets/JSON/2 Samuel/
    - assets/JSON/1 Kings/
    - assets/JSON/2 Kings/
    - assets/JSON/1 Chronicles/
    - assets/JSON/2 Chronicles/
    - assets/JSON/Ezra/
    - assets/JSON/Nehemiah/
    - assets/JSON/Esther/
    - assets/JSON/Job/
    - assets/JSON/Psalms/
    - assets/JSON/Proverbs/
    - assets/JSON/Ecclesiastes/
    - assets/JSON/Song of Solomon/
    - assets/JSON/Isaiah/
    - assets/JSON/Jeremiah/
    - assets/JSON/Lamentations/
    - assets/JSON/Ezekiel/
    - assets/JSON/Daniel/
    - assets/JSON/Hosea/
    - assets/JSON/Joel/
    - assets/JSON/Amos/
    - assets/JSON/Obadiah/
    - assets/JSON/Jonah/
    - assets/JSON/Micah/
    - assets/JSON/Nahum/
    - assets/JSON/Habakkuk/
    - assets/JSON/Zephaniah/
    - assets/JSON/Haggai/
    - assets/JSON/Zechariah/
    - assets/JSON/Malachi/
    - assets/JSON/Matthew/
    - assets/JSON/Mark/
    - assets/JSON/Luke/
    - assets/JSON/John/
    - assets/JSON/Acts/
    - assets/JSON/Romans/
    - assets/JSON/1 Corinthians/
    - assets/JSON/2 Corinthians/
    - assets/JSON/Galatians/
    - assets/JSON/Ephesians/
    - assets/JSON/Philippians/
    - assets/JSON/Colossians/
    - assets/JSON/1 Thessalonians/
    - assets/JSON/2 Thessalonians/
    - assets/JSON/1 Timothy/
    - assets/JSON/2 Timothy/
    - assets/JSON/Titus/
    - assets/JSON/Philemon/
    - assets/JSON/Hebrews/
    - assets/JSON/James/
    - assets/JSON/1 Peter/
    - assets/JSON/2 Peter/
    - assets/JSON/1 John/
    - assets/JSON/2 John/
    - assets/JSON/3 John/
    - assets/JSON/Jude/
    - assets/JSON/Revelation/
    - assets/Odiya_USX/
