// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcX_JbgLPKL7v1H_AaLb5XaTmYgQcLnGU',
    appId: '1:1042344895810:web:a47fc46b54ac1fc88994db',
    messagingSenderId: '1042344895810',
    projectId: 'odiyabible-6621f',
    authDomain: 'odiyabible-6621f.firebaseapp.com',
    storageBucket: 'odiyabible-6621f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcX_JbgLPKL7v1H_AaLb5XaTmYgQcLnGU',
    appId: '1:1042344895810:android:ANDROID_APP_ID_HERE',
    messagingSenderId: '1042344895810',
    projectId: 'odiyabible-6621f',
    storageBucket: 'odiyabible-6621f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcX_JbgLPKL7v1H_AaLb5XaTmYgQcLnGU',
    appId: '1:1042344895810:ios:IOS_APP_ID_HERE',
    messagingSenderId: '1042344895810',
    projectId: 'odiyabible-6621f',
    storageBucket: 'odiyabible-6621f.firebasestorage.app',
    iosBundleId: 'com.example.odiyaBibleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcX_JbgLPKL7v1H_AaLb5XaTmYgQcLnGU',
    appId: '1:1042344895810:ios:IOS_APP_ID_HERE',
    messagingSenderId: '1042344895810',
    projectId: 'odiyabible-6621f',
    storageBucket: 'odiyabible-6621f.firebasestorage.app',
    iosBundleId: 'com.example.odiyaBibleApp',
  );
}